#' generate time series for simulated data sets

#' simualted a time series of white noise with lenth n
white_noise <- function(n){
  return(rnorm(n))
}

#' integrate_ar1(x,rho)
#' integrates a time series x with coeficent rho
integrate_ar1 <- function(x,rho){
  x_int <- rep(0, length(x))
  x_0 <- 0
  i <- 0
  for(x_t in x){
    i <- i + 1
    x_0 <- x_t + rho*x_0
    x_int[i] <- x_0
  }
  return(x_int)
}

#' time_series(n, rho)
#' simualted a time series of length n integrated
#' length(rho) times with coeficent rho[i]
time_series <- function(n, rho){
  x <- white_noise(n)
  for(r in rho){
    x <- integrate_ar1(x, r) 
  }
  return((x - mean(x))/sd(x))
}


#' generate_X(n,m,rho)
#' geneates a matrix of values X with n rows
#' m columns where each colum is generated by 
#' the function time_series with paramters given by 
#' rho[i,] which is m by 3 matrix
generate_X <- function(n,m,rho){
  X <- matrix(0, nrow = n, ncol = m)
  for(i in 1:m){
    x <- time_series(n,rho[i,])
    X[,i] <- x
  }
  return(X)
}

#' generate_rho_matrix(m)
#' generates a rho matrix of length m
#' and width 3 each 
generate_rho_matrix <- function(m){
  vals <- sample(c(0,0,0.5), m*3, replace = T)
  return(matrix(vals, nrow = m, ncol = 3))
}




